server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  application:
    name: social-event-manager

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  jackson:
    time-zone: America/Argentina/Buenos_Aires

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    properties:
      sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";'
      ssl.truststore.password: ${KAFKA_TRUSTSTORE_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 #1 hour

app:
  frontend-url: ${FRONTEND_URL}
  backend-url: ${BACKEND_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL}
  override-to: ${RESEND_OVERRIDE_TO:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: social-event-manager
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          base-url: ${GRAFANA_REMOTE_WRITE_URL}
          job: social-event-manager
          username: ${GRAFANA_USERNAME}
          password: ${GRAFANA_API_TOKEN}
          push-rate: 60s

info:
  app:
    name: Social Event Manager
    version: 1.0.0
    java-version: 21
    description: Full-stack social event management application

mercadopago:
  access-token: ${MP_ACCESS_TOKEN}
  public-key: ${MP_PUBLIC_KEY}
  webhook-secret: ${MP_WEBHOOK_SECRET}
