server:
  port: 8080

spring:
  application:
    name: social-event-manager

  datasource:
    url: jdbc:postgresql://localhost:5433/social_event_manager
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: America/Argentina/Buenos_Aires

jwt:
  secret: my-calculator-is-casio-2026-coffee
  expiration: 86400000 #1 hour