server:
  port: 8080

spring:
  application:
    name: social-event-manager

  datasource:
    url: jdbc:postgresql://dpg-d8knvasvikkc73d924j0-a.oregon-postgres.render.com/social_event_manager_egeb
    username: social_event_manager_egeb_user
    password: mmz1F1NKYWDqOeabvZ9XFOPFSgCMynUg
  # datasource:
  #   url: jdbc:postgresql://localhost:5433/social_event_manager
  #   username: postgres
  #   password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: America/Argentina/Buenos_Aires

jwt:
  secret: my-calculator-is-casio-2026-coffee
  expiration: 86400000 #1 hour
